services:
  database:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: rootpass
      MYSQL_DATABASE: my_db
      MYSQL_USER: app
      MYSQL_PASSWORD: apppass
    volumes:
      - database_data:/var/lib/mysql
    ports:
      - "3306:3306"

  php:
    build:
      context: ./backend
      dockerfile: Dockerfile
    volumes:
      - ./backend:/var/www/html
    environment:
      DATABASE_URL: "mysql://app:apppass@database:3306/my_db?serverVersion=8&charset=utf8mb4"
    depends_on:
      - database
    ports:
      - "8000:80"

  node:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    volumes:
      - ./frontend:/app
    ports:
      - "3000:3000"
    command: npm start
    depends_on:
      - php

volumes:
  database_data:

